filter:
    excluded_paths:
        - 'src/Michalmanko/Holiday/Test/*'
checks:
    php:
        uppercase_constants: true
        use_self_instead_of_fqcn: true
        return_doc_comments: true
        properties_in_camelcaps: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        avoid_fixme_comments: true
        avoid_todo_comments: true
        classes_in_camel_caps: true
        function_in_camel_caps: true
        line_length:
            max_length: '120'
        naming_conventions:
            local_variable: '^[a-z][a-zA-Z0-9]*$'
            abstract_class_name: ^Abstract|Factory$
            utility_class_name: ''
            constant_name: '^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$'
            property_name: '^[a-z][a-zA-Z0-9]*$'
            method_name: '^(?:[a-z]|__)[a-zA-Z0-9]*$'
            parameter_name: '^[a-z][a-zA-Z0-9]*$'
            interface_name: '^[A-Z][a-zA-Z0-9]*Interface$'
            type_name: '^[A-Z][a-zA-Z0-9]*$'
            exception_name: '^[A-Z][a-zA-Z0-9]*Exception$'
            isser_method_name: ''
        newline_at_end_of_file: true
        no_goto: true
        no_long_variable_names:
            maximum: '30'
        no_short_method_names:
            minimum: '3'
        no_short_variable_names:
            minimum: '3'
        simplify_boolean_return: true
        optional_parameters_at_the_end: true
        encourage_single_quotes: true
        avoid_perl_style_comments: true
        fix_doc_comments: false

coding_style:
    php: { }